load("@rules_rust//rust:defs.bzl", "rust_static_library", "rust_library", "rust_binary")

# LLVM Compiler
cc_binary(
    name = "alkyl_llvm",
    srcs = glob([
        "src/codegen_llvm/**/*.c",
        "src/codegen_llvm/**/*.cpp",
        "src/codegen_llvm/**/*.h",
        "src/codegen_llvm/**/*.hpp",
        "src/driver/**/*.c",
        "src/driver/**/*.cpp",
        "src/driver/**/*.h",
        "src/diagnostic/**/*.c",
        "src/diagnostic/**/*.h",
        
        "src/common/**/*.c",
        "src/common/**/*.cpp",
        "src/common/**/*.h",
        "src/alir/**/*.c",
        "src/alir/**/*.cpp",
        "src/alir/**/*.h",
        "src/codegen/**/*.c",
        "src/codegen/**/*.cpp",
        "src/codegen/**/*.h",
        "src/alick/**/*.c",
        "src/alick/**/*.cpp",
        "src/alick/**/*.h",
        "src/metalir/**/*.c",
        "src/metalir/**/*.cpp",
        "src/metalir/**/*.h",
        "src/metarse/**/*.c",
        "src/metarse/**/*.cpp",
        "src/metarse/**/*.h",
        "src/optlir/**/*.c",
        "src/optlir/**/*.cpp",
        "src/optlir/**/*.h",
        "src/lexer/**/*.c",
        "src/lexer/**/*.h",
        "src/parser/**/*.c",
        "src/parser/**/*.h",
        "src/semantic/**/*.c",
        "src/semantic/**/*.h",
        "include/**/*.h",
        "include/**/*.hpp",
    ], exclude=["src/driver/cli.c"]),
    includes = ["include", "include/codegen_qbe", "include/codegen_llvm", "include/codegen_llvm/fragment", "include/metarse", "include/mlir", "include/mlir/tablegen", "include/parser", "include/parser/fragment", "include/optlir", "include/metalir", "include/lexer", "include/common", "include/alir", "include/alir/fragment", "include/semantic", "include/semantic/fragment", "include/semantic/modifier", "include/driver", "include/alick", "include/codegen", "src"],
    copts = ["-O3", "-std=gnu11", "-Iinclude", "-include", "stdbool.h", "-D_GNU_SOURCE"],
    linkopts = ["-lLLVM-22", "-lm"],
    data = glob(["lib/**/*"]),
)

# MLIR Compiler
cc_binary(
    name = "alkyl_mlir",
    srcs = glob([
        "src/codegen_mlir/**/*.c",
        "src/codegen_mlir/**/*.cpp",
        "src/codegen_mlir/**/*.h",
        "src/codegen_mlir/**/*.hpp",
        "src/driver/**/*.c",
        "src/driver/**/*.cpp",
        "src/driver/**/*.h",
        "src/diagnostic/**/*.c",
        "src/diagnostic/**/*.h",
        
        "src/common/**/*.c",
        "src/common/**/*.cpp",
        "src/common/**/*.h",
        "src/alir/**/*.c",
        "src/alir/**/*.cpp",
        "src/alir/**/*.h",
        "src/codegen/**/*.c",
        "src/codegen/**/*.cpp",
        "src/codegen/**/*.h",
        "src/alick/**/*.c",
        "src/alick/**/*.cpp",
        "src/alick/**/*.h",
        "src/metalir/**/*.c",
        "src/metalir/**/*.cpp",
        "src/metalir/**/*.h",
        "src/metarse/**/*.c",
        "src/metarse/**/*.cpp",
        "src/metarse/**/*.h",
        "src/optlir/**/*.c",
        "src/optlir/**/*.cpp",
        "src/optlir/**/*.h",
        "src/lexer/**/*.c",
        "src/lexer/**/*.h",
        "src/parser/**/*.c",
        "src/parser/**/*.h",
        "src/semantic/**/*.c",
        "src/semantic/**/*.h",
        "include/**/*.h",
        "include/**/*.hpp",
    ], exclude=["src/driver/cli.c"]),
    includes = ["include", "include/codegen_qbe", "include/codegen_llvm", "include/codegen_llvm/fragment", "include/metarse", "include/mlir", "include/mlir/tablegen", "include/parser", "include/parser/fragment", "include/optlir", "include/metalir", "include/lexer", "include/common", "include/alir", "include/alir/fragment", "include/semantic", "include/semantic/fragment", "include/semantic/modifier", "include/driver", "include/alick", "include/codegen", "src"],
    copts = ["-O3", "-std=gnu11", "-Iinclude", "-include", "stdbool.h", "-D_GNU_SOURCE"],
    linkopts = ["-lMLIR", "-lLLVM-22", "-lm"],
    data = glob(["lib/**/*"]),
)

# Cranelift Backend (Rust)
rust_static_library(
    name = "alkyl_cranelift_backend",
    srcs = glob(["src/codegen_cranelift/rust_backend/src/**/*.rs"]),
    edition = "2021",
    deps = [
    ],
)

# Cranelift Compiler
cc_binary(
    name = "alkyl_cranelift",
    srcs = glob([
        "src/codegen_cranelift/*.c",
        "src/codegen_cranelift/*.h",
        "src/codegen_cranelift/*.cpp",
        "src/driver/**/*.c",
        "src/driver/**/*.cpp",
        "src/driver/**/*.h",
        "src/diagnostic/**/*.c",
        "src/diagnostic/**/*.h",
        
        "src/common/**/*.c",
        "src/common/**/*.cpp",
        "src/common/**/*.h",
        "src/alir/**/*.c",
        "src/alir/**/*.cpp",
        "src/alir/**/*.h",
        "src/codegen/**/*.c",
        "src/codegen/**/*.cpp",
        "src/codegen/**/*.h",
        "src/alick/**/*.c",
        "src/alick/**/*.cpp",
        "src/alick/**/*.h",
        "src/metalir/**/*.c",
        "src/metalir/**/*.cpp",
        "src/metalir/**/*.h",
        "src/metarse/**/*.c",
        "src/metarse/**/*.cpp",
        "src/metarse/**/*.h",
        "src/optlir/**/*.c",
        "src/optlir/**/*.cpp",
        "src/optlir/**/*.h",
        "src/lexer/**/*.c",
        "src/lexer/**/*.h",
        "src/parser/**/*.c",
        "src/parser/**/*.h",
        "src/semantic/**/*.c",
        "src/semantic/**/*.h",
        "include/**/*.h",
        "include/**/*.hpp",
    ], exclude=["src/driver/cli.c"]),
    includes = ["include", "include/codegen_qbe", "include/codegen_llvm", "include/codegen_llvm/fragment", "include/metarse", "include/mlir", "include/mlir/tablegen", "include/parser", "include/parser/fragment", "include/optlir", "include/metalir", "include/lexer", "include/common", "include/alir", "include/alir/fragment", "include/semantic", "include/semantic/fragment", "include/semantic/modifier", "include/driver", "include/alick", "include/codegen", "src"],
    copts = ["-O3", "-std=gnu11", "-Iinclude", "-include", "stdbool.h", "-D_GNU_SOURCE"],
    deps = [
        ":alkyl_cranelift_backend",
    ],
    linkopts = ["-lm", "-lpthread", "-ldl"],
    data = glob(["lib/**/*"]),
)
